chore: format shell code with `shfmt`

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -17,7 +17,7 @@
 
 PS4='+ ${BASH_SOURCE:-$0}@${LINENO:-0}${FUNCNAME:+#${FUNCNAME}()}: '
 
-if [[ -n "${NO_COLOR:-}" ]] || ! colors="$(tput colors 2>/dev/null)" || (( "${colors:-0}" < 16 )); then
+if [[ -n ${NO_COLOR-} ]] || ! colors="$(tput colors 2> /dev/null)" || (("${colors:-0}" < 16)); then
   RED=''
   YELLOW=''
   ORANGE=''
@@ -49,8 +49,8 @@ RUNTEST_CALLED=0
 
 AUTOMATED_TESTING=1
 
-if ! toplevel="$(git rev-parse --show-toplevel 2>/dev/null)"; then
-  if ! toplevel="$(readlink -f "${BASH_SOURCE[0]%/*}/.." 2>/dev/null)"; then
+if ! toplevel="$(git rev-parse --show-toplevel 2> /dev/null)"; then
+  if ! toplevel="$(readlink -f "${BASH_SOURCE[0]%/*}/.." 2> /dev/null)"; then
     toplevel="${PWD:-$(pwd)}"
   fi
 fi
@@ -62,7 +62,7 @@ export PATH="${toplevel}${PATH:+:${PATH}}"
 unset toplevel
 
 function busctl2var {
-  if (( "$#" != 2 )); then
+  if (("$#" != 2)); then
     printf 1>&2 -- 'usage: %s VARIABLE_NAME BUSCTL_CALL\n' "${FUNCNAME[0]}"
     return 1
   fi
@@ -74,14 +74,14 @@ function busctl2var {
   # string-munging work with sed alone and not require `tr` in the pipeline.
   local varname_suffix
   varname_suffix="$(
-      printf -- '%s' "$1" \
-    | sed -e '
+    printf -- '%s' "$1" |
+      sed -e '
       s/[^[:alnum:]]//g
       s/\([a-z]\)\([A-Z]\)/\1_\2/g
       s/\([A-Z]\)\([A-Z][a-z]\)/\1_\2/g
-    ' \
-    | tr '[:lower:]' '[:upper:]' \
-    | sed 's/^SET_LINK_//'
+    ' |
+      tr '[:lower:]' '[:upper:]' |
+      sed 's/^SET_LINK_//'
   )"
 
   # `var_ref` is a reference variable; we use it by assigning to it.
@@ -94,9 +94,9 @@ function busctl {
   # unset or empty, assume this is the call from the "main" function in
   # update-systemd-resolved, rather than an automated test checking the
   # behaviour of "busctl status <...>".
-  case "${1:-}" in
+  case "${1-}" in
     status)
-      if [[ -n "${TEST_BUSCTL_STATUS_RC:-}" ]]; then
+      if [[ -n ${TEST_BUSCTL_STATUS_RC-} ]]; then
         busctl_called=1
         _log "busctl status: returning ${TEST_BUSCTL_STATUS_RC}"
         return "$TEST_BUSCTL_STATUS_RC"
@@ -111,7 +111,7 @@ function busctl {
   # Set that busctl has been called
   busctl_called=1
 
-  if (( "$#" < 1 )); then
+  if (("$#" < 1)); then
     _fail "busctl called without arguments"
     return
   fi
@@ -124,18 +124,18 @@ function busctl {
 
   local -a expected
 
-  if [[ -v "$indir" ]]; then
+  if [[ -v $indir ]]; then
     local -a expanded
-    read -r -a expanded <<<"${!indir}"
+    read -r -a expanded <<< "${!indir}"
 
-    if (( "$#" > 0 )); then
+    if (("$#" > 0)); then
       local signature="$1"
 
       local elem etype
       local -i i
-      for (( i = 0 ; i < "${#expanded[@]}"; i++ )); do
+      for ((i = 0; i < "${#expanded[@]}"; i++)); do
         elem="${expanded[${i}]}"
-        etype="${signature:${i}:1}"
+        etype="${signature:i:1}"
 
         # Support "true" and "false" for boolstrings; we expect these to be
         # coerced to "yes" and "no", respectively.  Similarly, support "yes"
@@ -143,22 +143,22 @@ function busctl {
         # "false", respectively.
         case "$elem" in
           true)
-            if [[ "$etype" == s ]]; then
+            if [[ $etype == s ]]; then
               elem=yes
             fi
             ;;
           false)
-            if [[ "$etype" == s ]]; then
+            if [[ $etype == s ]]; then
               elem=no
             fi
             ;;
           yes)
-            if [[ "$etype" == b ]]; then
+            if [[ $etype == b ]]; then
               elem=true
             fi
             ;;
           no)
-            if [[ "$etype" == b ]]; then
+            if [[ $etype == b ]]; then
               elem=false
             fi
             ;;
@@ -177,30 +177,30 @@ function busctl {
   case "$call" in
     SetLinkDNS)
       shift
-      if [[ "${TEST_BUSCTL_DNS}" == "" ]]; then
-        [[ "${ip_ifindex} ${TEST_BUSCTL_DNS}" == "$*" ]] || \
+      if [[ ${TEST_BUSCTL_DNS} == "" ]]; then
+        [[ "${ip_ifindex} ${TEST_BUSCTL_DNS}" == "$*" ]] ||
           _fail "SetLinkDNS was called and should not be: ${*@Q}"
-      elif [[ "${TEST_BUSCTL_DNS}" == SKIP ]]; then
-          :
+      elif [[ ${TEST_BUSCTL_DNS} == SKIP ]]; then
+        :
       elif [[ "${ip_ifindex} ${TEST_BUSCTL_DNS}" == "${*}" ]]; then
         _pass "SetLinkDNS was called correctly"
       else
         _fail "SetLinkDNS was not given the correct arguments:\n" \
-              "     Expected: ${ip_ifindex@Q} ${TEST_BUSCTL_DNS@Q}\n" \
-              "     Received: ${*@Q}"
+          "     Expected: ${ip_ifindex@Q} ${TEST_BUSCTL_DNS@Q}\n" \
+          "     Received: ${*@Q}"
       fi
       ;;
     SetLinkDomains)
       shift
-      if [[ "${TEST_BUSCTL_DOMAINS}" == "" ]]; then
-        [[ "${ip_ifindex} ${TEST_BUSCTL_DOMAINS}" == "$*" ]] || \
+      if [[ ${TEST_BUSCTL_DOMAINS} == "" ]]; then
+        [[ "${ip_ifindex} ${TEST_BUSCTL_DOMAINS}" == "$*" ]] ||
           _fail "SetLinkDomains was called and should not be: ${*@Q}"
       elif [[ "${ip_ifindex} ${TEST_BUSCTL_DOMAINS}" == "$*" ]]; then
-          _pass "SetLinkDomains was called correctly"
+        _pass "SetLinkDomains was called correctly"
       else
-          _fail "SetLinkDomains was not given the correct arguments:\n" \
-                "     Expected: ${ip_ifindex@Q} ${TEST_BUSCTL_DOMAINS@Q}\n" \
-                "     Received: ${*@Q}"
+        _fail "SetLinkDomains was not given the correct arguments:\n" \
+          "     Expected: ${ip_ifindex@Q} ${TEST_BUSCTL_DOMAINS@Q}\n" \
+          "     Received: ${*@Q}"
       fi
       ;;
     SetLinkDNSSEC)
@@ -209,27 +209,27 @@ function busctl {
         _pass "SetLinkDNSSEC was called correctly"
       else
         _fail "SetLinkDNSSEC was not given the correct arguments:\n" \
-              "     Expected: ${ip_ifindex@Q} ${TEST_BUSCTL_DNSSEC@Q}\n" \
-              "     Received: ${*@Q}"
+          "     Expected: ${ip_ifindex@Q} ${TEST_BUSCTL_DNSSEC@Q}\n" \
+          "     Received: ${*@Q}"
       fi
       ;;
-    FlushCaches|ResetServerFeatures|ResetStatistics)
-      if (( "${#expected[@]}" == 0 )); then
+    FlushCaches | ResetServerFeatures | ResetStatistics)
+      if (("${#expected[@]}" == 0)); then
         _fail "${call} was called unexpectedly"
         return
-      elif (( "$#" != 0 )); then
+      elif (("$#" != 0)); then
         _fail "${call} must be called with no arguments"
       fi
       ;;
-    SetLinkDNSOverTLS|SetLinkDefaultRoute|SetLinkLLMNR|SetLinkMulticastDNS)
-      if (( "${#expected[@]}" == 0 )); then
+    SetLinkDNSOverTLS | SetLinkDefaultRoute | SetLinkLLMNR | SetLinkMulticastDNS)
+      if (("${#expected[@]}" == 0)); then
         _fail "${call} was called unexpectedly"
         return
-      elif (( "$#" != 3 )); then
+      elif (("$#" != 3)); then
         _fail "${call} must be called with exactly three (3) arguments"
-      elif [[ "${expected[0]}" != "${if_index?}" ]]; then
+      elif [[ ${expected[0]} != "${if_index?}" ]]; then
         _fail "${call} not called with the expected interface index as first argument: expected ${if_index}, got ${expected[0]}"
-      elif [[ "$3" != "${expected[1]}" ]]; then
+      elif [[ $3 != "${expected[1]}" ]]; then
         _fail "${call} not called with the expected setting value: expected ${expected[1]}, got ${3}"
       fi
       ;;
@@ -263,10 +263,10 @@ function resolvectl {
 
 function logger {
   # Remove standard options
-  if [[ "$*" == *' --' ]]; then
+  if [[ $* == *' --' ]]; then
     set --
   else
-    while (( "$#" > 0 )); do
+    while (("$#" > 0)); do
       case "$1" in
         --)
           shift
@@ -279,7 +279,7 @@ function logger {
     done
   fi
 
-  if (( "$#" == 0 )) && ! [[ -t 0 ]]; then
+  if (("$#" == 0)) && ! [[ -t 0 ]]; then
     local message
     while read -r message; do
       _log "-- ${message}"
@@ -296,31 +296,31 @@ function exit {
 }
 
 function _log {
-  ( >&2 echo -e "    ${DARK}${*}${RESET}" )
+  (echo >&2 -e "    ${DARK}${*}${RESET}")
 }
 
 function _pass {
-  COUNT_PASS=$((COUNT_PASS+1))
-  ( >&2 echo -e "  ${GREEN}${PASS}${RESET} ${*}" )
+  COUNT_PASS=$((COUNT_PASS + 1))
+  (echo >&2 -e "  ${GREEN}${PASS}${RESET} ${*}")
 }
 
 function _fail {
-  COUNT_FAIL=$((COUNT_FAIL+1))
+  COUNT_FAIL=$((COUNT_FAIL + 1))
   if [[ -v TEST ]]; then
     FAILED["$TEST"]=1
   fi
-  ( >&2 echo -e "  ${RED}${FAIL} ${*}${RESET}" )
+  (echo >&2 -e "  ${RED}${FAIL} ${*}${RESET}")
 }
 
 function checktest() {
   # Increment counter so that we don't double-execute if a test script calls
   # this function.
   : ${RUNTEST_CALLED:=0}
-  (( RUNTEST_CALLED += 1 ))
+  ((RUNTEST_CALLED += 1))
 
   echo -e "${GREEN}- Testing ${TEST_TITLE:-a nameless test}${RESET}"
 
-  if (( $# < 1 )); then
+  if (($# < 1)); then
     set -- source update-systemd-resolved
   fi
 
@@ -330,23 +330,23 @@ function checktest() {
   "$@" || exit_status="$?"
   exit_message="script exited with a ${exit_status} exit status"
 
-  if [[ "$(( exit_status > 0 ))" == "${EXPECT_FAILURE:-0}" ]]; then
-      _pass "$exit_message"
+  if [[ "$((exit_status > 0))" == "${EXPECT_FAILURE:-0}" ]]; then
+    _pass "$exit_message"
   else
-      _fail "$exit_message"
+    _fail "$exit_message"
   fi
 }
 
 function runtest {
   checktest
 
-  if [[ "${TEST_BUSCTL_CALLED:-}" = 0 ]]; then
-    if (( busctl_called == 0 )); then
+  if [[ ${TEST_BUSCTL_CALLED-} == 0 ]]; then
+    if ((busctl_called == 0)); then
       _pass "busctl was not called, as expected"
     else
       _fail "busctl was called, not expected"
     fi
-  elif (( busctl_called == 0 )); then
+  elif ((busctl_called == 0)); then
     _fail "busctl was not called, not expected"
   fi
 
@@ -367,7 +367,7 @@ evaltest() {
   TEST_BUSCTL_FLUSH_CACHES=1
   TEST_BUSCTL_STATUS_RC=""
   # Keep this random, as we will never know the ifindex up-front
-  ip_ifindex=$((RANDOM%=64))
+  ip_ifindex=$((RANDOM %= 64))
   # Same for the device
   dev="tun${RANDOM}"
 
@@ -378,7 +378,7 @@ evaltest() {
   # shellcheck source-path=SCRIPTDIR source=tests/01_no_updates.sh
   source "$TEST" || return
 
-  if (( RUNTEST_CALLED > 0 )); then
+  if ((RUNTEST_CALLED > 0)); then
     return
   fi
 
@@ -387,7 +387,7 @@ evaltest() {
   local i=0
   local opt
   for opt in "${foreign_options[@]}" in; do
-    declare "foreign_option_$(( i += 1 ))=${opt}"
+    declare "foreign_option_$((i += 1))=${opt}"
   done
 
   runtest
@@ -396,14 +396,14 @@ evaltest() {
 echo "update-systemd-resolved Test Suite"
 echo
 
-if (( "$#" < 1 )); then
+if (("$#" < 1)); then
   set -- ./tests
 fi
 
 for path in "$@"; do
-  if [[ -d "$path" ]]; then
+  if [[ -d $path ]]; then
     for test in "$path"/*.sh; do
-      if [[ -f "$test" ]]; then
+      if [[ -f $test ]]; then
         evaltest "$test"
       fi
     done
@@ -415,7 +415,7 @@ done
 echo -e "  ${GREEN}${PASS} ${COUNT_PASS} Passed${RESET}"
 echo -e "  ${RED}${FAIL} ${COUNT_FAIL} Failed${RESET}"
 
-if [[ -v FAILED ]] && (( "${#FAILED[@]}" > 0 )); then
+if [[ -v FAILED ]] && (("${#FAILED[@]}" > 0)); then
   echo -e "\n  ${YELLOW}The following files have failing test cases:${RESET}"
 
   for failed in "${!FAILED[@]}"; do
@@ -424,4 +424,4 @@ if [[ -v FAILED ]] && (( "${#FAILED[@]}" > 0 )); then
 fi
 
 # Make sure we fail if there are failed tests
-(( COUNT_FAIL == 0 ))
+((COUNT_FAIL == 0))
