Add "print-polkit-rules" action
that prints a polkit rules definition to standard output. These rules
permit specified users and/or groups to perform the DBus calls necessary
for update-systemd-resolved's proper operation.

diff --git a/update-systemd-resolved b/update-systemd-resolved
--- a/update-systemd-resolved
+++ b/update-systemd-resolved
@@ -60,7 +60,7 @@ else
 fi
 
 usage() {
-  err "${1:?${1}. }. Usage: ${SCRIPT_NAME} up|down device_name."
+  err "${1:?${1}. }. Usage: ${SCRIPT_NAME} up|down|print-polkit-rules [<options>]."
 }
 
 busctl_call() {
@@ -68,6 +68,7 @@ busctl_call() {
   busctl call "$DBUS_DEST" "$DBUS_NODE" "${DBUS_DEST}.Manager" "$@" || {
     local -i status=$?
     err "'busctl' exited with status $status"
+    print_polkit_rules_command_for_current_user | err
     return $status
   }
 }
@@ -249,7 +250,38 @@ puts_with_separator() {
   printf -- '\n'
 }
 
-up() {
+with_openvpn_script_handling() {
+  if (( "$#" == 0 )); then
+    usage 'No script type specified'
+    return 1
+  fi
+
+  local func="$1"
+  shift || :
+
+  local dev="${1:-${dev:-}}"
+  shift || :
+
+  if [[ -z "${dev:-}" ]]; then
+    usage 'No device name specified'
+    return 1
+  fi
+
+  if ! read -r link if_index _ < <(get_link_info "$dev"); then
+    usage "Invalid device name: '$dev'"
+    return 1
+  fi
+
+  if ! "$func" "$link" "$if_index" "$@"; then
+    err 'Unable to configure systemd-resolved.'
+    return 1
+  fi
+
+  # Flush the DNS cache
+  busctl_call FlushCaches
+}
+
+_up() {
   local link="$1"
   shift
   local if_index="$1"
@@ -313,18 +345,25 @@ up() {
   fi
 }
 
+up() {
+  with_openvpn_script_handling _up "$@"
+}
+
 down() {
+  with_openvpn_script_handling _down "$@"
+}
+
+_down() {
   local link="$1"
   shift
   local if_index="$1"
   shift
 
   info "Link '$link' going down"
-  if [[ "$(whoami 2>/dev/null)" != "root" ]]; then
-    # Cleanly handle the privilege dropped case by not calling RevertLink
-    info "Privileges dropped in the client: Cannot call RevertLink."
-  else
-    busctl_call RevertLink i "$if_index"
+
+  if ! busctl_call RevertLink i "$if_index"; then
+    info 'Calling RevertLink failed; this can happen if privileges were dropped in the OpenVPN client.'
+    print_polkit_rules_command_for_current_user | info
   fi
 }
 
@@ -865,35 +904,246 @@ process_dnssec() {
   dns_sec="${setting}"
 }
 
-main() {
-  local script_type="${1}"
-  shift
-  local dev="${1:-$dev}"
+if command -v jq &>/dev/null; then
+  to_json_array() {
+    jq --compact-output --null-input '$ARGS.positional' --args -- "$@"
+  }
+else
+  to_json_array() {
+    printf -- '['
+
+    while (( "$#" > 0 )); do
+      printf -- '"%s"' "${1//\"/\\\"}"
+      shift
+      if (( "$#" > 0 )); then
+        printf -- ','
+      fi
+    done
+
+    printf -- ']'
+  }
+fi
+
+require_optarg() {
+  local opt="$1"
   shift
 
-  if [[ -z "$script_type" ]]; then
-    usage 'No script type specified'
-    return 1
-  elif [[ -z "$dev" ]]; then
-    usage 'No device name specified'
-    return 1
-  elif ! declare -f "${script_type}" &>/dev/null; then
-    usage "Invalid script type: '${script_type}'"
-    return 1
-  else
-    if ! read -r link if_index _ < <(get_link_info "$dev"); then
-      usage "Invalid device name: '$dev'"
-      return 1
-    fi
+  local argc="$1"
+  shift
 
-    "$script_type" "$link" "$if_index" "$@" || return 1
-    # Flush the DNS cache
-    busctl_call FlushCaches
+  if (( argc < 2 )); then
+    err "missing required argument for option \"$opt\""
+    return 1
   fi
+}
+
+# shellcheck disable=SC2120
+print_polkit_rules() {
+  local -A allowed_users_map=() allowed_groups_map=() systemd_openvpn_units_map=()
+
+  while (( "$#" > 0 )); do
+    case "$1" in
+      --polkit-allowed-user)
+        require_optarg "$1" "$#" || return
+        allowed_users_map["${2?}"]=1
+        shift
+        ;;
+      --polkit-allowed-user=?*)
+        allowed_users_map["${1#*=}"]=1
+        ;;
+      --polkit-allowed-group)
+        require_optarg "$1" "$#" || return
+        allowed_groups_map["${2?}"]=1
+        shift
+        ;;
+      --polkit-allowed-group=?*)
+        allowed_groups_map["${1#*=}"]=1
+        ;;
+      --polkit-systemd-openvpn-unit)
+        require_optarg "$1" "$#" || return
+        systemd_openvpn_units_map["${2?}"]=1
+        shift
+        ;;
+      --polkit-systemd-openvpn-unit=?*)
+        systemd_openvpn_units_map["${1#*=}"]=1
+        ;;
+      *)
+        err "unrecognized option: $1"
+        return 1
+        ;;
+    esac
+
+    shift
+  done
+
+  if {
+        (( "${#systemd_openvpn_units_map[@]}" < 1 )) \
+    &&  (( "${#allowed_users_map[@]}" < 1 )) \
+    &&  (( "${#allowed_groups_map[@]}" < 1 ))
+  }; then
+    # NOTE that we cannot use the template unit "openvpn-client@.service"
+    # itself:
+    #
+	#   $ systemctl show -p User openvpn-client@.service
+    #   Failed to get properties: Unit name openvpn-client@.service is neither a valid invocation ID nor unit name.
+    #   $ systemctl show -p User openvpn-client@utterly-bogus.service
+    #   User=openvpn
+    #
+    systemd_openvpn_units_map["openvpn-client@totally-made-up-to-avoid-collisions-${RANDOM:-12345}.service"]=1
+  fi
+
+  local allowed_user
+  while read -r allowed_user; do
+    if [[ -n "${allowed_user:-}" ]]; then
+      allowed_users_map["$allowed_user"]=1
+    fi
+  done < <(systemctl show -P User "${!systemd_openvpn_units_map[@]}" 2>/dev/null)
+
+  if (( ${#allowed_users_map[@]} < 1 )); then
+    warning 'unable to determine the value(s) of "User=..." for OpenVPN client systemd units; assuming "root".'
+    allowed_users_map[root]=1
+  fi
+
+  local allowed_group
+  while read -r allowed_group; do
+    if [[ -n "${allowed_group:-}" ]]; then
+      allowed_groups_map["$allowed_group"]=1
+    fi
+  done < <(systemctl show -P Group "${!systemd_openvpn_units_map[@]}" 2>/dev/null)
+
+  if (( ${#allowed_groups_map[@]} < 1 )); then
+    err 'unable to determine the value(s) of "Group=..." for OpenVPN client systemd units; assuming "root".'
+    allowed_groups_map[root]=1
+  fi
+
+  local allowed_users allowed_groups
+  allowed_users="$(to_json_array "${!allowed_users_map[@]}")" || return
+  allowed_groups="$(to_json_array "${!allowed_groups_map[@]}")" || return
+
+  printf -- \
+'/*
+ * Allow OpenVPN client services to update systemd-resolved settings.
+ * Added by %s.
+ */
+
+function listToBoolMap(list) {
+  var result = {};
+
+  for (var i = 0; i < list.length; i++) {
+    var item = list[i];
+    result[item] = true;
+  }
+
+  return result;
+}
+
+const updateSystemdResolved = {
+  allowedUsers: listToBoolMap(%s),
+
+  allowedGroups: %s,
+
+  allowedSubactions: listToBoolMap([
+    "set-dns-servers",
+    "set-domains",
+    "set-dnssec",
+    "revert",
+  ]),
+
+  actionIsAllowed: function(action) {
+    if ( !action.id.startsWith("org.freedesktop.resolve1.") ) {
+      return false;
+    }
+
+    var ns = action.id.split(".");
+    var subaction = ns[ns.length - 1];
+
+    return this.allowedSubactions[subaction];
+  },
+
+  subjectIsAllowed: function(subject) {
+    if ( this.allowedUsers[subject.user] ) {
+      return true;
+    }
+
+    return this.allowedGroups.some(function(group) {
+      subject.isInGroup(group);
+    });
+  },
+
+  isAllowed: function(action, subject) {
+    return this.actionIsAllowed(action) && this.subjectIsAllowed(subject);
+  }
+};
+
+polkit.addRule(function(action, subject) {
+  if ( updateSystemdResolved.isAllowed(action, subject) ) {
+    return polkit.Result.YES;
+  } else {
+    return polkit.Result.NOT_HANDLED;
+  }
+});
+' "$SCRIPT_NAME" "$allowed_users" "$allowed_groups"
+}
+
+print_polkit_rules_command_for_current_user() {
+  local current_user current_group
+
+  local format='You may wish to add the output of the following command'
+  format+=' to your polkit rules in order to authorize your user to access'
+  format+=' the systemd-resolved DBus interface:'
+  format+='\n%q print-polkit-rules'
+
+  local -a args=("$SCRIPT_NAME")
+
+  if current_user="$(id -u -n 2>/dev/null)" && [[ -n "${current_user:-}" ]]; then
+    format+=' --polkit-allowed-user %q'
+    args+=("$current_user")
+  fi
+
+  if current_group="$(id -g -n 2>/dev/null)" && [[ -n "${current_group:-}" ]]; then
+    format+=' --polkit-allowed-group %q'
+    args+=("$current_group")
+  fi
+
+  format+='\nPlease see %s for additional details on configuring polkit.\n'
+  args+=('https://github.com/tomeon/update-systemd-resolved/tree/polkit-rules-definition#policykit-rules')
+
+  # shellcheck disable=SC2059
+  printf -- "$format" "${args[@]}"
+}
+
+main() {
+  local action
+  while (( "$#" > 0 )); do
+    case "$1" in
+      up|down|print-polkit-rules)
+        action="$1"
+        ;;
+      --)
+        shift
+        break
+        ;;
+      *)
+        break
+        ;;
+    esac
+
+    shift
+  done
+
+  action="${action:-${script_type:-down}}"
+  action="${action//-/_}"
+
+  if ! declare -f "${action}" &>/dev/null; then
+    usage "Invalid script type: '${action}'"
+    return 1
+  fi
+
+  "$action" "$@"
 }
 
 if [[ "${BASH_SOURCE[0]}" == "$0" ]] || [[ "${AUTOMATED_TESTING:-}" == 1 ]]; then
   set -o nounset
 
-  main "${script_type:-down}" "$@"
+  main "$@"
 fi
